import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { Loader2, ExternalLink, RefreshCw, FileCode, Bot, Globe, Copy, Check } from "lucide-react";

/**
 * SitemapRobotsEditor — manage the dynamic sitemap.xml + robots.txt.
 *
 * sitemap.xml and robots.txt are generated by edge functions (`/functions/v1/sitemap`
 * and `/functions/v1/robots`). This UI lets admins:
 *   1. Set a public Site URL (used for <loc> + Sitemap: line).
 *   2. Override robots.txt content with a textarea.
 *   3. Preview both files live (re-fetches from the edge function).
 *   4. Copy public URLs to paste into Google Search Console / Bing Webmaster.
 */

const DEFAULT_ROBOTS = `User-agent: *
Allow: /

User-agent: Googlebot
Allow: /

User-agent: Bingbot
Allow: /

# {{SITEMAP_URL}} is replaced automatically with the live sitemap URL
Sitemap: {{SITEMAP_URL}}
`;

const PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID as string;
const FN_BASE = `https://${PROJECT_ID}.supabase.co/functions/v1`;

const SitemapRobotsEditor = () => {
  const { toast } = useToast();
  const qc = useQueryClient();

  const [siteUrl, setSiteUrl] = useState("");
  const [robotsTxt, setRobotsTxt] = useState(DEFAULT_ROBOTS);
  const [saving, setSaving] = useState(false);
  const [sitemapPreview, setSitemapPreview] = useState<string | null>(null);
  const [robotsPreview, setRobotsPreview] = useState<string | null>(null);
  const [loadingSitemap, setLoadingSitemap] = useState(false);
  const [loadingRobots, setLoadingRobots] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);

  // Load existing global SEO settings
  const { data: globals, isLoading } = useQuery({
    queryKey: ["seo-global-settings"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("site_content")
        .select("*")
        .eq("page", "seo")
        .eq("section", "global");
      if (error) throw error;
      return data;
    },
  });

  useEffect(() => {
    if (!globals) return;
    const su = globals.find((g) => g.content_key === "site_url");
    const rb = globals.find((g) => g.content_key === "robots_txt");
    if (su) setSiteUrl(su.value || "");
    if (rb) setRobotsTxt(rb.value || DEFAULT_ROBOTS);
  }, [globals]);

  const upsert = async (key: string, value: string, contentType = "text") => {
    const existing = globals?.find((g) => g.content_key === key);
    if (existing) {
      const { error } = await supabase
        .from("site_content")
        .update({ value, content_type: contentType })
        .eq("id", existing.id);
      if (error) throw error;
    } else {
      const { error } = await supabase.from("site_content").insert({
        page: "seo",
        section: "global",
        content_key: key,
        value,
        content_type: contentType,
        sort_order: 0,
      });
      if (error) throw error;
    }
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      const cleanUrl = siteUrl.trim().replace(/\/$/, "");
      await upsert("site_url", cleanUrl);
      await upsert("robots_txt", robotsTxt);
      qc.invalidateQueries({ queryKey: ["seo-global-settings"] });
      toast({ title: "Saved", description: "Sitemap & robots.txt settings updated." });
      // refresh previews
      setSitemapPreview(null);
      setRobotsPreview(null);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Unknown error";
      toast({ title: "Save failed", description: message, variant: "destructive" });
    } finally {
      setSaving(false);
    }
  };

  const fetchPreview = async (which: "sitemap" | "robots") => {
    const setter = which === "sitemap" ? setSitemapPreview : setRobotsPreview;
    const setLoading = which === "sitemap" ? setLoadingSitemap : setLoadingRobots;
    setLoading(true);
    try {
      const res = await fetch(`${FN_BASE}/${which}?_=${Date.now()}`);
      const text = await res.text();
      setter(text);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Unknown error";
      toast({ title: "Preview failed", description: message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const copy = (label: string, value: string) => {
    navigator.clipboard.writeText(value);
    setCopied(label);
    setTimeout(() => setCopied(null), 1500);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-16 text-muted-foreground">
        <Loader2 className="animate-spin mr-2" size={18} /> Loading…
      </div>
    );
  }

  const sitemapUrl = `${FN_BASE}/sitemap`;
  const robotsUrl = `${FN_BASE}/robots`;
  const publicSitemap = (siteUrl.trim().replace(/\/$/, "") || "https://your-domain.com") + "/sitemap.xml";
  const publicRobots = (siteUrl.trim().replace(/\/$/, "") || "https://your-domain.com") + "/robots.txt";

  return (
    <div className="space-y-6">
      {/* Intro */}
      <div className="flex items-start gap-3 bg-accent/5 border border-accent/20 rounded-xl p-4">
        <FileCode size={20} className="text-accent shrink-0 mt-0.5" />
        <div>
          <h3 className="font-semibold text-foreground text-sm">Sitemap & robots.txt</h3>
          <p className="text-xs text-muted-foreground mt-1">
            Your sitemap is generated automatically from the published navigation structure, including nested subpages, plus dynamic content like blog posts.
          </p>
        </div>
      </div>

      {/* Site URL */}
      <div>
        <Label className="text-sm font-medium flex items-center gap-1.5">
          <Globe size={14} className="text-muted-foreground" />
          Public site URL
        </Label>
        <p className="text-[11px] text-muted-foreground mt-1 mb-2">
          The full URL of your live site (no trailing slash). Used in <code className="px-1 py-0.5 bg-muted rounded text-foreground">{`<loc>`}</code> tags and the <code className="px-1 py-0.5 bg-muted rounded text-foreground">Sitemap:</code> line.
        </p>
        <Input
          type="url"
          placeholder="https://www.digitizeme.ae"
          value={siteUrl}
          onChange={(e) => setSiteUrl(e.target.value)}
        />
      </div>

      {/* Public URLs */}
      <div className="bg-card border border-border rounded-xl p-4 space-y-3">
        <h4 className="text-sm font-semibold text-foreground">Public URLs to submit</h4>
        <p className="text-[11px] text-muted-foreground">
          Add these to Google Search Console & Bing Webmaster Tools.
        </p>
        {[
          { label: "Sitemap", value: publicSitemap },
          { label: "Robots", value: publicRobots },
        ].map((item) => (
          <div key={item.label} className="flex items-center gap-2 bg-muted/30 border border-border/50 rounded-lg p-2">
            <span className="text-[10px] font-semibold uppercase text-muted-foreground w-14">{item.label}</span>
            <code className="flex-1 text-xs text-foreground truncate font-mono">{item.value}</code>
            <Button
              type="button"
              size="sm"
              variant="ghost"
              onClick={() => copy(item.label, item.value)}
              className="h-7 px-2"
            >
              {copied === item.label ? <Check size={14} className="text-emerald-500" /> : <Copy size={14} />}
            </Button>
          </div>
        ))}
        <p className="text-[11px] text-muted-foreground">
          ⚠️ For these URLs to work on your domain, you must proxy <code className="px-1 py-0.5 bg-muted rounded">/sitemap.xml</code> and{" "}
          <code className="px-1 py-0.5 bg-muted rounded">/robots.txt</code> on your hosting/CDN to the edge functions
          shown in the previews below. Until you do, search engines will see the static fallback files.
        </p>
      </div>

      {/* Robots.txt editor */}
      <div>
        <Label className="text-sm font-medium flex items-center gap-1.5">
          <Bot size={14} className="text-muted-foreground" />
          robots.txt content
        </Label>
        <p className="text-[11px] text-muted-foreground mt-1 mb-2">
          Use <code className="px-1 py-0.5 bg-muted rounded">{`{{SITEMAP_URL}}`}</code> as a placeholder — it's replaced automatically with your live sitemap URL.
        </p>
        <Textarea
          value={robotsTxt}
          onChange={(e) => setRobotsTxt(e.target.value)}
          rows={12}
          className="font-mono text-xs"
        />
        <div className="flex gap-2 mt-2">
          <Button
            type="button"
            size="sm"
            variant="ghost"
            onClick={() => setRobotsTxt(DEFAULT_ROBOTS)}
            className="text-xs"
          >
            Reset to default
          </Button>
        </div>
      </div>

      {/* Save button */}
      <div className="flex justify-end pt-2 border-t border-border">
        <Button onClick={handleSave} disabled={saving} className="bg-accent text-accent-foreground hover:bg-accent/90">
          {saving ? <><Loader2 className="animate-spin mr-2" size={16} /> Saving…</> : "Save settings"}
        </Button>
      </div>

      {/* Previews */}
      <div className="grid md:grid-cols-2 gap-4 pt-4 border-t border-border">
        {/* Sitemap preview */}
        <div className="bg-card border border-border rounded-xl p-4">
          <div className="flex items-center justify-between mb-2">
            <h4 className="text-sm font-semibold text-foreground flex items-center gap-1.5">
              <FileCode size={14} /> sitemap.xml preview
            </h4>
            <div className="flex gap-1">
              <Button size="sm" variant="ghost" onClick={() => fetchPreview("sitemap")} disabled={loadingSitemap} className="h-7 px-2">
                {loadingSitemap ? <Loader2 className="animate-spin" size={14} /> : <RefreshCw size={14} />}
              </Button>
              <a href={sitemapUrl} target="_blank" rel="noreferrer">
                <Button size="sm" variant="ghost" className="h-7 px-2">
                  <ExternalLink size={14} />
                </Button>
              </a>
            </div>
          </div>
          {sitemapPreview ? (
            <pre className="text-[10px] font-mono bg-muted/40 border border-border/50 rounded-lg p-3 max-h-72 overflow-auto whitespace-pre-wrap text-foreground">
              {sitemapPreview}
            </pre>
          ) : (
            <button
              onClick={() => fetchPreview("sitemap")}
              className="w-full text-xs text-muted-foreground hover:text-foreground border border-dashed border-border rounded-lg py-6"
            >
              Click to load preview
            </button>
          )}
        </div>

        {/* Robots preview */}
        <div className="bg-card border border-border rounded-xl p-4">
          <div className="flex items-center justify-between mb-2">
            <h4 className="text-sm font-semibold text-foreground flex items-center gap-1.5">
              <Bot size={14} /> robots.txt preview
            </h4>
            <div className="flex gap-1">
              <Button size="sm" variant="ghost" onClick={() => fetchPreview("robots")} disabled={loadingRobots} className="h-7 px-2">
                {loadingRobots ? <Loader2 className="animate-spin" size={14} /> : <RefreshCw size={14} />}
              </Button>
              <a href={robotsUrl} target="_blank" rel="noreferrer">
                <Button size="sm" variant="ghost" className="h-7 px-2">
                  <ExternalLink size={14} />
                </Button>
              </a>
            </div>
          </div>
          {robotsPreview ? (
            <pre className="text-[10px] font-mono bg-muted/40 border border-border/50 rounded-lg p-3 max-h-72 overflow-auto whitespace-pre-wrap text-foreground">
              {robotsPreview}
            </pre>
          ) : (
            <button
              onClick={() => fetchPreview("robots")}
              className="w-full text-xs text-muted-foreground hover:text-foreground border border-dashed border-border rounded-lg py-6"
            >
              Click to load preview
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default SitemapRobotsEditor;
