UPDATE public.blog_posts SET title_ar='الفوترة الإلكترونية لمنظومة ETA في مصر 2026: الدليل الكامل لامتثال الشركات', excerpt_ar='كل ما تحتاج كل شركة مصرية إلى معرفته عن منظومة الفوترة الإلكترونية لمصلحة الضرائب في 2026 — العقوبات، وقواعد ضريبة القيمة المضافة، وسير العمل، وكيف تجعل أتمتة المستندات بالذكاء الاصطناعي الامتثال يستغرق دقائق بدلاً من ساعات.', content_ar='<p class="lead"><strong>الفواتير الإلكترونية لمنظومة ETA في مصر</strong> لم تعد اختيارية. فمنذ أن أكملت مصلحة الضرائب المصرية (ETA) تطبيقها المرحلي، أصبح من الإلزامي إصدار كل معاملة بين الشركات (B2B) ومعاملة مع الحكومة (B2G) كفاتورة إلكترونية عبر البوابة الوطنية. يترتب على عدم الامتثال غرامات تصل إلى <strong>50,000 جنيه مصري لكل مخالفة</strong> ويؤدي إلى عدم أهليتك للمطالبة بخصم ضريبة المدخلات (VAT). يشرح هذا الدليل بالتحديد كيف يعمل النظام في عام 2026، وما يجب على كل شركة مصرية القيام به، وكيف تقلل أتمتة المستندات المدعومة بالذكاء الاصطناعي (AI) عبء العمل بنسبة 90%.</p>

<div class="grid grid-cols-2 md:grid-cols-4 gap-3 my-8 not-prose"><div class="rounded-2xl border bg-gradient-to-br from-rose-500/15 to-rose-500/5 border-rose-400/30 text-rose-500 p-5 text-center not-prose"><div class="text-3xl md:text-4xl font-bold leading-none">50 ألف جنيه مصري</div><div class="mt-2 text-xs uppercase tracking-wider opacity-80">الحد الأقصى للغرامة لكل مخالفة</div></div><div class="rounded-2xl border bg-gradient-to-br from-indigo-500/15 to-indigo-500/5 border-indigo-400/30 text-indigo-500 p-5 text-center not-prose"><div class="text-3xl md:text-4xl font-bold leading-none">100%</div><div class="mt-2 text-xs uppercase tracking-wider opacity-80">التغطية المطلوبة لمعاملات B2B</div></div><div class="rounded-2xl border bg-gradient-to-br from-emerald-500/15 to-emerald-500/5 border-emerald-400/30 text-emerald-500 p-5 text-center not-prose"><div class="text-3xl md:text-4xl font-bold leading-none">90%</div><div class="mt-2 text-xs uppercase tracking-wider opacity-80">عمل يدوي أقل مع الـ AI</div></div><div class="rounded-2xl border bg-gradient-to-br from-indigo-500/15 to-indigo-500/5 border-indigo-400/30 text-indigo-500 p-5 text-center not-prose"><div class="text-3xl md:text-4xl font-bold leading-none">14 يومًا</div><div class="mt-2 text-xs uppercase tracking-wider opacity-80">وقت التنفيذ النموذجي</div></div></div>

<h2>ما هي الفوترة الإلكترونية لمنظومة ETA ومن يجب عليه الامتثال؟</h2>
<p>يُلزم <strong>نظام الفوترة الإلكترونية لمصلحة الضرائب المصرية</strong> كل دافع ضرائب مسجل بإصدار الفواتير عبر بوابة ETA بصيغة XML/JSON منظمة، وموقعة باستخدام توكن USB (التوقيع الإلكتروني) ومعتمدة في الوقت الفعلي. ويشمل هذا الإلزام:</p>
<ul>
  <li>جميع الشركات المسجلة في ضريبة القيمة المضافة (VAT) (بغض النظر عن حجمها أو قطاعها)</li>
  <li>كيانات المناطق الحرة التي تتاجر مع السوق المحلي</li>
  <li>مقدمو الخدمات، والمصنعون، والتجار، والشركات المهنية</li>
  <li>الموردون للحكومة (معاملات B2G إلزامية بالكامل)</li>
</ul>

<h2>أين تهدر الفرق المالية المصرية الساعات كل أسبوع</h2>
<figure class="my-10 not-prose"><div class="rounded-2xl border border-border bg-card p-6"><div class="text-sm font-semibold text-foreground mb-4">الساعات الأسبوعية المهدرة في مهام الفوترة لمنظومة ETA (متوسط شركة مصرية صغيرة ومتوسطة بها 50 موظفًا)</div><svg viewBox="0 0 600 290" class="w-full h-auto" role="img" aria-label="Weekly hours lost on ETA invoicing"><text x="0" y="44" font-size="12" fill="hsl(var(--foreground))" font-weight="600" text-anchor="end" direction="rtl" x="600">إعادة إدخال بيانات الفاتورة في بوابة ETA</text><rect x="0" y="50" width="500" height="20" rx="4" fill="hsl(var(--muted))" opacity="0.4" /><rect x="0" y="50" width="380" height="20" rx="4" fill="hsl(var(--accent))" /><text x="420" y="64" font-size="12" fill="hsl(var(--foreground))" font-weight="700" text-anchor="end" direction="rtl" x="590">19 ساعة</text><text x="0" y="90" font-size="12" fill="hsl(var(--foreground))" font-weight="600" text-anchor="end" direction="rtl" x="600">إصلاح الفواتير المرفوضة</text><rect x="0" y="96" width="500" height="20" rx="4" fill="hsl(var(--muted))" opacity="0.4" /><rect x="0" y="96" width="180" height="20" rx="4" fill="hsl(var(--accent))" /><text x="220" y="110" font-size="12" fill="hsl(var(--foreground))" font-weight="700" text-anchor="end" direction="rtl" x="590">9 ساعات</text><text x="0" y="136" font-size="12" fill="hsl(var(--foreground))" font-weight="600" text-anchor="end" direction="rtl" x="600">مطابقة الأكواد الضريبية (HS / GS1)</text><rect x="0" y="142" width="500" height="20" rx="4" fill="hsl(var(--muted))" opacity="0.4" /><rect x="0" y="142" width="140" height="20" rx="4" fill="hsl(var(--accent))" /><text x="180" y="156" font-size="12" fill="hsl(var(--foreground))" font-weight="700" text-anchor="end" direction="rtl" x="590">7 ساعات</text><text x="0" y="182" font-size="12" fill="hsl(var(--foreground))" font-weight="600" text-anchor="end" direction="rtl" x="600">متابعة العملاء (بسبب الفواتير الإلكترونية المرفوضة)</text><rect x="0" y="188" width="500" height="20" rx="4" fill="hsl(var(--muted))" opacity="0.4" /><rect x="0" y="188" width="120" height="20" rx="4" fill="hsl(var(--accent))" /><text x="160" y="202" font-size="12" fill="hsl(var(--foreground))" font-weight="700" text-anchor="end" direction="rtl" x="590">6 ساعات</text><text x="0" y="228" font-size="12" fill="hsl(var(--foreground))" font-weight="600" text-anchor="end" direction="rtl" x="600">التسوية الشهرية لـ VAT</text><rect x="0" y="234" width="500" height="20" rx="4" fill="hsl(var(--muted))" opacity="0.4" /><rect x="0" y="234" width="160" height="20" rx="4" fill="hsl(var(--accent))" /><text x="200" y="248" font-size="12" fill="hsl(var(--foreground))" font-weight="700" text-anchor="end" direction="rtl" x="590">8 ساعات</text></svg></div></figure>

<p>هذا يمثل ما يقرب من <strong>50 ساعة أسبوعيًا</strong> لشركة مصرية واحدة متوسطة الحجم — وهو عمل يجب أن يستغرق 5 ساعات فقط مع وجود أتمتة المستندات المناسبة.</p>

<h2>سير عمل الفوترة الإلكترونية المتوافق مع ETA باستخدام الـ AI</h2>
<figure class="my-10 not-prose"><div class="rounded-2xl border border-border bg-card p-6"><div class="text-sm font-semibold text-foreground mb-4">من مستند المبيعات إلى فاتورة معتمدة من ETA</div><svg viewBox="0 0 600 130" class="w-full h-auto" role="img" aria-label="ETA e-invoicing workflow"><circle cx="60.0" cy="50" r="22" fill="hsl(var(--accent))"/><text x="60.0" y="56" font-size="16" font-weight="700" fill="white" text-anchor="middle">5</text><text x="60.0" y="100" font-size="11" font-weight="600" fill="hsl(var(--foreground))" text-anchor="middle">أرشفة لمدة 5 سنوات</text><line x1="82.0" y1="50" x2="158.0" y2="50" stroke="hsl(var(--accent))" stroke-width="2" stroke-dasharray="4 4" opacity="0.5"/><circle cx="180.0" cy="50" r="22" fill="hsl(var(--accent))"/><text x="180.0" y="56" font-size="16" font-weight="700" fill="white" text-anchor="middle">4</text><text x="180.0" y="100" font-size="11" font-weight="600" fill="hsl(var(--foreground))" text-anchor="middle">توقيع وإرسال</text><line x1="202.0" y1="50" x2="278.0" y2="50" stroke="hsl(var(--accent))" stroke-width="2" stroke-dasharray="4 4" opacity="0.5"/><circle cx="300.0" cy="50" r="22" fill="hsl(var(--accent))"/><text x="300.0" y="56" font-size="16" font-weight="700" fill="white" text-anchor="middle">3</text><text x="300.0" y="100" font-size="11" font-weight="600" fill="hsl(var(--foreground))" text-anchor="middle">ربط بـ GS1</text><line x1="322.0" y1="50" x2="398.0" y2="50" stroke="hsl(var(--accent))" stroke-width="2" stroke-dasharray="4 4" opacity="0.5"/><circle cx="420.0" cy="50" r="22" fill="hsl(var(--accent))"/><text x="420.0" y="56" font-size="16" font-weight="700" fill="white" text-anchor="middle">2</text><text x="420.0" y="100" font-size="11" font-weight="600" fill="hsl(var(--foreground))" text-anchor="middle">استخلاص بـ AI</text><line x1="442.0" y1="50" x2="518.0" y2="50" stroke="hsl(var(--accent))" stroke-width="2" stroke-dasharray="4 4" opacity="0.5"/><circle cx="540.0" cy="50" r="22" fill="hsl(var(--accent))"/><text x="540.0" y="56" font-size="16" font-weight="700" fill="white" text-anchor="middle">1</text><text x="540.0" y="100" font-size="11" font-weight="600" fill="hsl(var(--foreground))" text-anchor="middle">تسجيل البيع</text></svg></div></figure>

<h2>بوابة ETA اليدوية مقابل الأتمتة المدعومة بالـ AI</h2>
<div class="my-8 overflow-x-auto rounded-xl border border-border not-prose"><table class="w-full text-sm"><thead class="bg-muted/50"><tr><th class="text-right py-3 px-4 font-semibold">المهمة</th><th class="text-right py-3 px-4 font-semibold">بوابة ETA اليدوية</th><th class="text-right py-3 px-4 font-semibold text-emerald-600">مع Digitize me</th></tr></thead><tbody><tr class="border-t border-border"><td class="py-3 px-4 font-medium text-right">إصدار فاتورة B2B واحدة</td><td class="py-3 px-4 text-muted-foreground text-right">8-12 دقيقة من الإدخال اليدوي</td><td class="py-3 px-4 font-semibold text-emerald-600 text-right">12 ثانية، مؤتمتة بالكامل</td></tr><tr class="border-t border-border"><td class="py-3 px-4 font-medium text-right">ربط خط المنتجات بكود GS1 / EGS</td><td class="py-3 px-4 text-muted-foreground text-right">جداول بحث، أخطاء متكررة</td><td class="py-3 px-4 font-semibold text-emerald-600 text-right">الـ AI يقترح ويطبق تلقائيًا عمليات الربط المكتسبة</td></tr><tr class="border-t border-border"><td class="py-3 px-4 font-medium text-right">التوقيع باستخدام توكن USB</td><td class="py-3 px-4 text-muted-foreground text-right">موظف واحد، جهاز واحد، اختناق في العمل</td><td class="py-3 px-4 font-semibold text-emerald-600 text-right">توقيع HSM من جانب الخادم للفريق بأكمله</td></tr><tr class="border-t border-border"><td class="py-3 px-4 font-medium text-right">إرسال دفعة من 1000+ فاتورة</td><td class="py-3 px-4 text-muted-foreground text-right">مشروع يستغرق عدة أيام</td><td class="py-3 px-4 font-semibold text-emerald-600 text-right">دفعة واحدة، في أقل من 30 دقيقة</td></tr><tr class="border-t border-border"><td class="py-3 px-4 font-medium text-right">مطابقة الفواتير الإلكترونية للموردين لخصم VAT</td><td class="py-3 px-4 text-muted-foreground text-right">مطابقة ثلاثية يدوية</td><td class="py-3 px-4 font-semibold text-emerald-600 text-right">مطابقة تلقائية مع أمر الشراء (PO) وإشعار استلام البضاعة (GRN)</td></tr></tbody></table></div>

<div class="not-prose my-6 border-r-4 border-r-amber-400 bg-amber-500/5 p-4 rounded-l-lg text-right"><p class="text-sm text-foreground"><span class="ml-2">⚠️</span>أغلى خطأ نراه في مصر بخصوص منظومة ETA هو التعامل مع الفوترة الإلكترونية كمشروع لتقنية المعلومات. إنها <strong>سير عمل مالي وتشغيلي</strong> — والوفورات تكمن في التخلص من إعادة إدخال البيانات، وليس في البوابة نفسها.</p></div>

<h2>عقوبات ETA التي يجب معرفتها في 2026</h2>
<ul>
  <li><strong>عدم التسجيل</strong> في نظام الفوترة الإلكترونية: تصل إلى 50,000 جنيه مصري</li>
  <li><strong>إصدار فاتورة ورقية</strong> بدلاً من فاتورة إلكترونية: نفس الغرامة، تتكرر مع كل مخالفة</li>
  <li><strong>قبول المشتري لفاتورة غير متوافقة:</strong> يفقد حق خصم ضريبة المدخلات (VAT) (وهو ما يكون غالبًا أشد إيلامًا من الغرامة)</li>
  <li><strong>التأخر في الإرسال:</strong> فوائد + عقوبات إدارية</li>
</ul>

<h2>ميزات خاصة بمصر تهمك في منصة المستندات</h2>
<ul>
  <li>تقنية <strong>OCR أصلية باللغة العربية</strong> لفواتير الموردين والمستندات الداعمة</li>
  <li>مكتبة أكواد <strong>EGS / GS1 مدمجة</strong> لتصنيف المنتجات المصرية</li>
  <li>تكامل مباشر مع <strong>ETA API</strong> (بدون تحميل يدوي على البوابة)</li>
  <li>توقيع إلكتروني من جانب الخادم (بدون اختناق بسبب توكن USB)</li>
  <li>استضافة في مصر أو في مراكز بيانات إقليمية متوافقة</li>
  <li>واجهة مستخدم ثنائية اللغة (عربي / إنجليزي) للموظفين في القاهرة والإسكندرية والدلتا</li>
</ul>

<h2>خطة تنفيذ لمدة 14 يومًا لشركة مصرية صغيرة ومتوسطة</h2>
<ul>
  <li><strong>الأيام 1-2:</strong> ربط نظام ERP / المحاسبة (SAP, Odoo, Microsoft Dynamics, المتكامل)</li>
  <li><strong>الأيام 3-5:</strong> ربط كتالوج المنتجات بأكواد EGS / GS1 (بمساعدة AI)</li>
  <li><strong>الأيام 6-8:</strong> نقل توقيع توكن USB إلى HSM من جانب الخادم</li>
  <li><strong>الأيام 9-11:</strong> تدريب الفريق المالي، تشغيل إصدار موازٍ</li>
  <li><strong>الأيام 12-14:</strong> بدء التشغيل الفعلي، ومراقبة أول 100 فاتورة إلكترونية، والتحسين</li>
</ul>

<section class="not-prose my-10"><h2 class="text-2xl font-bold mb-4">الأسئلة الشائعة</h2><div class="space-y-2"><details class="group rounded-xl border border-border bg-card p-5 open:bg-muted/30 transition-colors"><summary class="cursor-pointer list-none flex items-center justify-between gap-4 font-semibold text-foreground"><span>هل الفوترة الإلكترونية لمنظومة ETA إلزامية للشركات الصغيرة في مصر؟</span><span class="text-accent group-open:rotate-45 transition-transform text-xl leading-none">+</span></summary><div class="mt-3 text-sm text-muted-foreground leading-relaxed">نعم. اكتمل التطبيق المرحلي - يجب على كل دافع ضرائب مسجل في ضريبة القيمة المضافة (VAT) في مصر، بغض النظر عن حجمه، إصدار فواتير B2B و B2G من خلال نظام ETA.</div></details><details class="group rounded-xl border border-border bg-card p-5 open:bg-muted/30 transition-colors"><summary class="cursor-pointer list-none flex items-center justify-between gap-4 font-semibold text-foreground"><span>هل ما زلت بحاجة إلى توكن USB في عام 2026؟</span><span class="text-accent group-open:rotate-45 transition-transform text-xl leading-none">+</span></summary><div class="mt-3 text-sm text-muted-foreground leading-relaxed">لا تزال توكنات USB الشخصية شائعة، لكن معظم العملاء من الشركات المتوسطة والكبيرة قد انتقلوا إلى التوقيعات الإلكترونية عبر HSM من جانب الخادم، والتي تسمح لعدة موظفين بإصدار الفواتير بالتوازي دون مشاركة توكن مادي واحد.</div></details><details class="group rounded-xl border border-border bg-card p-5 open:bg-muted/30 transition-colors"><summary class="cursor-pointer list-none flex items-center justify-between gap-4 font-semibold text-foreground"><span>هل يمكن للمنصة التعامل مع فواتير الموردين باللغة العربية؟</span><span class="text-accent group-open:rotate-45 transition-transform text-xl leading-none">+</span></summary><div class="mt-3 text-sm text-muted-foreground leading-relaxed">نعم. تقوم تقنية OCR الأصلية باللغة العربية باستخلاص بيانات المورد والإجمالي وضريبة القيمة المضافة (VAT) والبنود من فواتير الموردين المصرية المعتادة، بما في ذلك المكتوبة بخط اليد، ومطابقتها مع أوامر الشراء الخاصة بك.</div></details><details class="group rounded-xl border border-border bg-card p-5 open:bg-muted/30 transition-colors"><summary class="cursor-pointer list-none flex items-center justify-between gap-4 font-semibold text-foreground"><span>ما هي المدة التي يجب أن أحتفظ فيها بالفواتير الإلكترونية في مصر؟</span><span class="text-accent group-open:rotate-45 transition-transform text-xl leading-none">+</span></summary><div class="mt-3 text-sm text-muted-foreground leading-relaxed">يتطلب قانون الضرائب المصري الاحتفاظ بالسجلات المحاسبية والضريبية لمدة 5 سنوات على الأقل. وتعد منصة المستندات التي تحتوي على ميزة الأرشفة هي أبسط طريقة لتلبية هذا المتطلب.</div></details></div></section>

<div class="not-prose my-10 rounded-2xl p-8 md:p-10 text-center" style="background:linear-gradient(135deg,hsl(var(--primary)),hsl(var(--primary)/0.85));color:hsl(var(--primary-foreground))"><h3 class="text-2xl md:text-3xl font-bold mb-2">شاهد إصدار فاتورة إلكترونية مصرية في 12 ثانية</h3><p class="opacity-90 mb-6 max-w-xl mx-auto" style="color:hsl(var(--primary-foreground))">أحضر عينة من فاتورة مبيعات وكتالوج EGS الخاص بك. سنتصل بالبيئة التجريبية (sandbox) لمنظومة ETA ونرسل فاتورة إلكترونية موقعة بالكامل مباشرة خلال العرض التوضيحي الخاص بك.</p><a href="/contact" class="inline-flex items-center gap-2 rounded-full px-6 py-3 font-semibold hover:opacity-90 transition" style="background:hsl(var(--accent))!important;color:hsl(var(--accent-foreground))">احجز عرضًا توضيحيًا لمصر ←</a></div>' WHERE slug='eta-einvoicing-egypt-2026-complete-guide';