INSERT INTO public.testimonials (author_name, role, company, quote, rating, featured, published, sort_order) VALUES
('Omar Al Marzooqi','Managing Partner','Al Marzooqi Law Firm','We used to lose half an hour per case file search. Now our paralegals pull any contract or court filing in seconds, and access is locked down per lawyer.',5,false,true,100),
('Fatima Haddad','Senior Associate','Gulf Law Chambers','Client confidentiality was our biggest worry with paper archives. Role-based access solved it, and our filing room is finally empty.',5,false,true,101),
('Rami Nasser','Audit Director','Meridian Accounting Group','Audit prep dropped from three days to an afternoon. Every client folder exports audit-ready in one click.',5,false,true,102),
('Layla Kassem','Partner','Horizon Accounting Consultants','No more chasing which version of a financial statement is final. One authoritative copy per client, searchable by tax year.',5,false,true,103),
('Khalid Bin Sulayem','Operations Manager','Emirates Logistics Solutions','A disputed waybill used to cost us a full day. Our drivers now pull customs papers from their phones at the port.',5,false,true,104),
('Sanjay Menon','Fleet Supervisor','Falcon Logistics & Transport','Customs clearance delays are basically gone. Everything is indexed by shipment and route.',5,false,true,105),
('Mariam Al Zaabi','Sales Director','Skyline Real Estate','Property files, KYC, and contracts finally live in one place, and each party only sees what they should.',5,false,true,106),
('Tarek Haddad','Broker Manager','Pearl Real Estate Group','KYC expiry alerts alone saved us two compliance headaches this year.',5,false,true,107),
('Dr. Noura Al Amiri','Medical Records Lead','Al Amiri Healthcare Clinics','Inspections used to be a scramble. Now every patient record is complete and retrievable in seconds.',5,false,true,108),
('Dr. Yousef Karim','Clinic Director','Vitality Healthcare Center','Insurance claim packaging in one click cut our reimbursement cycle dramatically.',5,false,true,109),
('Huda Al Balushi','Registrar','Crescent Education Academy','Alumni certificate requests took days. We now return them in under a minute.',5,false,true,110),
('Peter Okafor','Head of Accreditation','Nexus Education & Training Institute','Accreditation documents with renewal alerts turned our inspections into a formality.',5,false,true,111),
('Ahmed Shaker','Quality Manager','Gulf Manufacturing Industries','ISO audit prep went from weeks to hours, with full lot traceability behind every batch record.',5,false,true,112),
('Elena Petrova','Compliance Officer','Prime Manufacturing Works','Supplier certificate expiry alerts have prevented at least three production stoppages.',5,false,true,113),
('Saeed Al Nuaimi','Project Director','Al Nuaimi Construction','Site teams always work off the latest drawing revision now. Rework from outdated plans has stopped.',5,false,true,114),
('Michael Trent','Document Controller','Arabian Construction Group','Permits are retrievable from any site office. No more stop-work notices over missing paperwork.',5,false,true,115),
('Hessa Al Suwaidi','Director of Digital Services','Government Services Authority','Decades of paper archives are now searchable, and citizen record retrieval takes seconds instead of days.',5,false,true,116),
('Abdulla Rashed','Head of Records','Municipal Government Department','Digital approvals between departments removed the paper courier entirely.',5,false,true,117),
('Nadia Farouk','Compliance Head','Union Banking Group','KYC completeness indicators show gaps before the regulator does. That changed how calm audits feel.',5,false,true,118),
('Imran Qureshi','Risk Manager','Capital Banking & Finance','Retention policies are enforced automatically now, which was previously a manual spreadsheet nightmare.',5,false,true,119),
('Waleed Barakat','Trade Operations Manager','Barakat Import & Export Co.','Letters of credit and customs declarations are organized by shipment. Our clearance turnaround improved noticeably.',5,false,true,120),
('Grace Mensah','Documentation Lead','Continental Import Export Trading','Every trade document is one search away, by supplier or by date.',5,false,true,121),
('Faisal Al Dhaheri','HSE Manager','Northern Oil & Gas Services','Safety certificates and equipment records are always current and auditable. Inspections no longer disrupt operations.',5,false,true,122),
('Robert Hines','Compliance Supervisor','Delta Oil and Gas Field Services','Environmental reporting files are consolidated instead of spread across five drives.',5,false,true,123),
('Amal Zayed','Claims Manager','Sahara Insurance Company','Claims documentation is processed far faster now, and nothing gets misfiled between departments.',5,false,true,124),
('Daniel Cruz','Underwriting Lead','Gulf Shield Insurance','Policy documents and endorsements are versioned properly for the first time.',5,false,true,125),
('Reem Al Hosani','Operations Head','Bloom Retail Group','Supplier invoices and receipts are captured and searchable, which made month-end reconciliation painless.',5,false,true,126),
('Vikram Shah','Finance Manager','Metro Retail & E-Commerce','Our store paperwork is finally centralized across every branch.',5,false,true,127);