UPDATE public.blog_posts SET content_ar='<p class="lead">دخل <strong>قانون حماية البيانات الشخصية المصري رقم 151 لسنة 2020 (PDPL)</strong> حيز التنفيذ بالكامل، ويقوم مركز حماية البيانات المصري بمراجعة الشكاوى بفعالية. إذا كانت شركتك تخزن بيانات KYC للعملاء، أو ملفات الموظفين، أو عقود الموردين، أو أي بيانات شخصية أخرى — وهو ما تفعله كل الشركات المصرية الصغيرة والمتوسطة تقريبًا — فيجب عليك الامتثال. تصل الغرامات إلى <strong>5 ملايين جنيه مصري عن كل مخالفة</strong>، والمخالفات العمدية تترتب عليها عقوبات جنائية. هذا الدليل هو النسخة المبسطة باللغة العربية والإنجليزية لما يجب على شركتك القيام به، وكيف يمكن لمنصة مستندات حديثة أن توفر عليك 90% من المجهود.</p>

<div class="grid grid-cols-2 md:grid-cols-4 gap-3 my-8 not-prose"><div class="rounded-2xl border bg-gradient-to-br from-rose-500/15 to-rose-500/5 border-rose-400/30 text-rose-500 p-5 text-center not-prose"><div class="text-3xl md:text-4xl font-bold leading-none">EGP 5M</div><div class="mt-2 text-xs uppercase tracking-wider opacity-80">أقصى غرامة للمخالفة الواحدة</div></div><div class="rounded-2xl border bg-gradient-to-br from-indigo-500/15 to-indigo-500/5 border-indigo-400/30 text-indigo-500 p-5 text-center not-prose"><div class="text-3xl md:text-4xl font-bold leading-none">72 h</div><div class="mt-2 text-xs uppercase tracking-wider opacity-80">مهلة الإبلاغ عن الاختراق</div></div><div class="rounded-2xl border bg-gradient-to-br from-emerald-500/15 to-emerald-500/5 border-emerald-400/30 text-emerald-500 p-5 text-center not-prose"><div class="text-3xl md:text-4xl font-bold leading-none">AES-256</div><div class="mt-2 text-xs uppercase tracking-wider opacity-80">المعيار الأساسي للتشفير</div></div><div class="rounded-2xl border bg-gradient-to-br from-indigo-500/15 to-indigo-500/5 border-indigo-400/30 text-indigo-500 p-5 text-center not-prose"><div class="text-3xl md:text-4xl font-bold leading-none">30 days</div><div class="mt-2 text-xs uppercase tracking-wider opacity-80">للاستعداد للمراجعة</div></div></div>

<h2>الالتزامات الستة التي يفرضها قانون PDPL المصري على شركتك</h2>
<ol>
  <li><strong>أساس قانوني لمعالجة البيانات الشخصية</strong> — موافقة، أو عقد، أو التزام قانوني، أو مصلحة مشروعة</li>
  <li><strong>حقوق صاحب البيانات</strong> — الوصول، والتصحيح، والحذف، والنقل، والاعتراض</li>
  <li><strong>تعيين مسؤول حماية بيانات (DPO)</strong> عندما تصل المعالجة إلى الحد التنظيمي</li>
  <li><strong>ترخيص نقل البيانات عبر الحدود</strong> — يتطلب نقل البيانات الشخصية المصرية إلى الخارج موافقة مركز حماية البيانات</li>
  <li><strong>الإبلاغ عن الاختراق خلال 72 ساعة</strong> للمركز والأفراد المتأثرين</li>
  <li><strong>ضمانات فنية</strong> — التشفير، والتحكم في الوصول، وسجلات المراجعة، وقواعد الاحتفاظ</li>
</ol>

<h2>أكثر الثغرات التي تعرض الشركات المصرية للمخاطر اليوم</h2>
<figure class="my-10 not-prose"><div class="rounded-2xl border border-border bg-card p-6" dir="rtl"><div class="text-sm font-semibold text-foreground mb-4">نسبة الشركات المصرية الصغيرة والمتوسطة التي لديها هذه الثغرة في الامتثال لقانون PDPL (من عينة المراجعة لعام 2025)</div><svg viewBox="0 0 600 290" class="w-full h-auto" role="img" aria-label="Egyptian SME PDPL gaps"><text x="600" y="44" font-size="12" fill="hsl(var(--foreground))" font-weight="600" text-anchor="end">ملفات KYC في البريد الإلكتروني الشخصي / WhatsApp</text><rect x="100" y="50" width="500" height="20" rx="4" fill="hsl(var(--muted))" opacity="0.4"/><rect x="155" y="50" width="445" height="20" rx="4" fill="hsl(var(--accent))"/><text x="147" y="64" font-size="12" fill="hsl(var(--foreground))" font-weight="700" text-anchor="end">89%</text><text x="600" y="90" font-size="12" fill="hsl(var(--foreground))" font-weight="600" text-anchor="end">لا توجد قواعد موثقة للاحتفاظ بالبيانات</text><rect x="100" y="96" width="500" height="20" rx="4" fill="hsl(var(--muted))" opacity="0.4"/><rect x="215" y="96" width="385" height="20" rx="4" fill="hsl(var(--accent))"/><text x="207" y="110" font-size="12" fill="hsl(var(--foreground))" font-weight="700" text-anchor="end">77%</text><text x="600" y="136" font-size="12" fill="hsl(var(--foreground))" font-weight="600" text-anchor="end">بيانات العملاء على منصات SaaS خارجية بدون ترخيص</text><rect x="100" y="142" width="500" height="20" rx="4" fill="hsl(var(--muted))" opacity="0.4"/><rect x="240" y="142" width="360" height="20" rx="4" fill="hsl(var(--accent))"/><text x="232" y="156" font-size="12" fill="hsl(var(--foreground))" font-weight="700" text-anchor="end">72%</text><text x="600" y="182" font-size="12" fill="hsl(var(--foreground))" font-weight="600" text-anchor="end">لا يوجد سجل مراجعة لمن قام بالوصول إلى أي ملف</text><rect x="100" y="188" width="500" height="20" rx="4" fill="hsl(var(--muted))" opacity="0.4"/><rect x="265" y="188" width="335" height="20" rx="4" fill="hsl(var(--accent))"/><text x="257" y="202" font-size="12" fill="hsl(var(--foreground))" font-weight="700" text-anchor="end">67%</text><text x="600" y="228" font-size="12" fill="hsl(var(--foreground))" font-weight="600" text-anchor="end">لا توجد خطة للاستجابة للاختراقات</text><rect x="100" y="234" width="500" height="20" rx="4" fill="hsl(var(--muted))" opacity="0.4"/><rect x="190" y="234" width="410" height="20" rx="4" fill="hsl(var(--accent))"/><text x="182" y="248" font-size="12" fill="hsl(var(--foreground))" font-weight="700" text-anchor="end">82%</text></svg></div></figure>

<h2>حزمة أمان المستندات التي تفي بالفعل بمتطلبات قانون PDPL المصري</h2>
<figure class="my-10 not-prose"><div class="rounded-2xl border border-border bg-card p-6"><div class="text-sm font-semibold text-foreground mb-4">5 طبقات تحول مراجعة PDPL إلى إجراء روتيني</div><svg viewBox="0 0 600 130" class="w-full h-auto" role="img" aria-label="PDPL layers"><circle cx="60.0" cy="50" r="22" fill="hsl(var(--accent))"/><text x="60.0" y="56" font-size="16" font-weight="700" fill="white" text-anchor="middle">5</text><text x="60.0" y="100" font-size="11" font-weight="600" fill="hsl(var(--foreground))" text-anchor="middle">إقامة بيانات متوافقة</text><line x1="82.0" y1="50" x2="158.0" y2="50" stroke="hsl(var(--accent))" stroke-width="2" stroke-dasharray="4 4" opacity="0.5"/><circle cx="180.0" cy="50" r="22" fill="hsl(var(--accent))"/><text x="180.0" y="56" font-size="16" font-weight="700" fill="white" text-anchor="middle">4</text><text x="180.0" y="100" font-size="11" font-weight="600" fill="hsl(var(--foreground))" text-anchor="middle">تشفير AES-256</text><line x1="202.0" y1="50" x2="278.0" y2="50" stroke="hsl(var(--accent))" stroke-width="2" stroke-dasharray="4 4" opacity="0.5"/><circle cx="300.0" cy="50" r="22" fill="hsl(var(--accent))"/><text x="300.0" y="56" font-size="16" font-weight="700" fill="white" text-anchor="middle">3</text><text x="300.0" y="100" font-size="11" font-weight="600" fill="hsl(var(--foreground))" text-anchor="middle">صلاحيات RBAC</text><line x1="322.0" y1="50" x2="398.0" y2="50" stroke="hsl(var(--accent))" stroke-width="2" stroke-dasharray="4 4" opacity="0.5"/><circle cx="420.0" cy="50" r="22" fill="hsl(var(--accent))"/><text x="420.0" y="56" font-size="16" font-weight="700" fill="white" text-anchor="middle">2</text><text x="420.0" y="100" font-size="11" font-weight="600" fill="hsl(var(--foreground))" text-anchor="middle">سجل مراجعة غير قابل للتغيير</text><line x1="442.0" y1="50" x2="518.0" y2="50" stroke="hsl(var(--accent))" stroke-width="2" stroke-dasharray="4 4" opacity="0.5"/><circle cx="540.0" cy="50" r="22" fill="hsl(var(--accent))"/><text x="540.0" y="56" font-size="16" font-weight="700" fill="white" text-anchor="middle">1</text><text x="540.0" y="100" font-size="11" font-weight="600" fill="hsl(var(--foreground))" text-anchor="middle">احتفاظ تلقائي</text></svg></div></figure>

<h2>الامتثال اليدوي مقابل منصة المستندات</h2>
<div class="my-8 overflow-x-auto rounded-xl border border-border not-prose"><table class="w-full text-sm"><thead class="bg-muted/50"><tr><th class="text-right py-3 px-4 font-semibold">متطلبات قانون PDPL</th><th class="text-right py-3 px-4 font-semibold">الأسلوب اليدوي / جداول البيانات</th><th class="text-right py-3 px-4 font-semibold text-emerald-600">مع Digitize me</th></tr></thead><tbody><tr class="border-t border-border"><td class="py-3 px-4 font-medium">تحديد جميع ملفات KYC لعميل معين</td><td class="py-3 px-4 text-muted-foreground">ساعات، وغالبًا ما تكون غير مكتملة</td><td class="py-3 px-4 font-semibold text-emerald-600">بحث واحد، نتيجة فورية</td></tr><tr class="border-t border-border"><td class="py-3 px-4 font-medium">الاستجابة لطلب حذف البيانات</td><td class="py-3 px-4 text-muted-foreground">خطر وجود نسخ منسية</td><td class="py-3 px-4 font-semibold text-emerald-600">محو بنقرة واحدة عبر المنصة بأكملها</td></tr><tr class="border-t border-border"><td class="py-3 px-4 font-medium">إثبات من قام بالوصول إلى ملف الموارد البشرية</td><td class="py-3 px-4 text-muted-foreground">مستحيل</td><td class="py-3 px-4 font-semibold text-emerald-600">سجل مراجعة كامل وغير قابل للتغيير</td></tr><tr class="border-t border-border"><td class="py-3 px-4 font-medium">تطبيق قواعد الاحتفاظ لمدة 5 / 7 / 10 سنوات</td><td class="py-3 px-4 text-muted-foreground">حذف يدوي، يسهل تفويته</td><td class="py-3 px-4 font-semibold text-emerald-600">سياسات تلقائية لكل مجلد</td></tr><tr class="border-t border-border"><td class="py-3 px-4 font-medium">الامتثال لنقل البيانات عبر الحدود</td><td class="py-3 px-4 text-muted-foreground">ملفات على منصات SaaS خارجية بشكل روتيني</td><td class="py-3 px-4 font-semibold text-emerald-600">إقامة بيانات إقليمية متوافقة بشكل افتراضي</td></tr></tbody></table></div>

<div class="not-prose my-6 border-r-4 border-l-0 border-r-rose-400 bg-rose-500/5 p-4 rounded-l-lg"><p class="text-sm text-foreground"><span class="ml-2">⚠️</span>أخطر وأكثر ثغرة مكلفة نراها في الامتثال لقانون PDPL المصري: فرق الموارد البشرية التي تشارك صور بطاقات الرقم القومي للموظفين عبر مجموعات WhatsApp. يمكن أن تصل غرامة مخالفة واحدة من هذا القبيل إلى <strong>مليون جنيه مصري</strong> — إن اعتماد سير عمل مركزي للمشاركة الآمنة يزيل هذا الخطر بالكامل في يوم واحد.</p></div>

<h2>خطة الاستعداد للامتثال لقانون PDPL المصري في 30 يومًا</h2>
<ul>
  <li><strong>الأسبوع الأول — الجرد:</strong> حدد جميع الأماكن التي توجد بها البيانات الشخصية (البريد الإلكتروني، ومحركات الأقراص، والملفات الورقية، ومنصات SaaS التابعة لجهات خارجية)</li>
  <li><strong>الأسبوع الثاني — النقل:</strong> انقل المستندات الحساسة إلى منصة مشفرة ذات وصول مُتحكَم فيه وتتمتع بإقامة بيانات متوافقة</li>
  <li><strong>الأسبوع الثالث — الحوكمة:</strong> طبق صلاحيات الوصول المستندة إلى الأدوار، وقواعد الاحتفاظ، وروابط المشاركة الآمنة؛ وقم بتدريب الموظفين على أساسيات قانون PDPL</li>
  <li><strong>الأسبوع الرابع — التوثيق:</strong> قم بإصدار أول تقرير مراجعة، وصياغة إشعار الخصوصية، وإعداد مذكرة امتثال داخلية، وتقديم إيجاز للإدارة</li>
</ul>

<h2>ما الذي سيتغير لعملائك</h2>
<p>بعيدًا عن تجنب الغرامات، أصبح الامتثال لقانون PDPL <strong>ميزة تجارية</strong>. فالبنوك المصرية والشركات متعددة الجنسيات والمناقصات الحكومية تطلب بشكل متزايد من الموردين ما يثبت امتثالهم للقانون. إن وجود برنامج موثق — وليس مجرد أداة — هو ما يفوز بالعقود.</p>

<section class="not-prose my-10"><h2 class="text-2xl font-bold mb-4">أسئلة شائعة</h2><div class="space-y-2"><details class="group rounded-xl border border-border bg-card p-5 open:bg-muted/30 transition-colors"><summary class="cursor-pointer list-none flex items-center justify-between gap-4 font-semibold text-foreground"><span class="text-accent group-open:-rotate-45 transition-transform text-xl leading-none">+</span><span>هل ينطبق قانون PDPL المصري على شركتي الصغيرة؟</span></summary><div class="mt-3 text-sm text-muted-foreground leading-relaxed">نعم. ينطبق القانون 151/2020 على أي كيان يعالج البيانات الشخصية للمقيمين في مصر — بغض النظر عن الحجم أو القطاع أو ما إذا كنت في القاهرة أو الإسكندرية أو الدلتا أو إحدى المناطق الحرة.</div></details><details class="group rounded-xl border border-border bg-card p-5 open:bg-muted/30 transition-colors"><summary class="cursor-pointer list-none flex items-center justify-between gap-4 font-semibold text-foreground"><span class="text-accent group-open:-rotate-45 transition-transform text-xl leading-none">+</span><span>هل يمكنني تخزين بيانات العملاء المصريين على AWS / Azure في الخارج؟</span></summary><div class="mt-3 text-sm text-muted-foreground leading-relaxed">فقط بعد الحصول على ترخيص نقل بيانات عبر الحدود من مركز حماية البيانات المصري، أو بالاعتماد على إطار ملائمة معتمد. بالنسبة لمعظم الشركات الصغيرة والمتوسطة، فإن اختيار منصة ذات إقامة بيانات إقليمية متوافقة هو أبسط وأقل تكلفة بكثير.</div></details><details class="group rounded-xl border border-border bg-card p-5 open:bg-muted/30 transition-colors"><summary class="cursor-pointer list-none flex items-center justify-between gap-4 font-semibold text-foreground"><span class="text-accent group-open:-rotate-45 transition-transform text-xl leading-none">+</span><span>هل يجب عليّ تعيين مسؤول حماية بيانات (DPO)؟</span></summary><div class="mt-3 text-sm text-muted-foreground leading-relaxed">يُعد تعيين DPO ضروريًا عند معالجة بيانات شخصية حساسة أو كميات كبيرة من البيانات أو المراقبة الممنهجة للأفراد. تعين العديد من الشركات المصرية الصغيرة والمتوسطة DPO بدوام جزئي أو تستعين بمستشار خارجي للامتثال للقانون بتكلفة فعالة.</div></details><details class="group rounded-xl border border-border bg-card p-5 open:bg-muted/30 transition-colors"><summary class="cursor-pointer list-none flex items-center justify-between gap-4 font-semibold text-foreground"><span class="text-accent group-open:-rotate-45 transition-transform text-xl leading-none">+</span><span>ما هي العقوبة في أسوأ الحالات؟</span></summary><div class="mt-3 text-sm text-muted-foreground leading-relaxed">تصل الغرامات الإدارية إلى 5 ملايين جنيه مصري لكل مخالفة؛ وتضيف المخالفات العمدية أو المتكررة مسؤولية جنائية على المديرين التنفيذيين. غالبًا ما يتجاوز الضرر الذي يلحق بالسمعة وفقدان العقود قيمة الغرامة نفسها.</div></details></div></section>

<div class="not-prose my-10 rounded-2xl p-8 md:p-10 text-center" style="background:linear-gradient(135deg,hsl(var(--primary)),hsl(var(--primary)/0.85));color:hsl(var(--primary-foreground))"><h3 class="text-2xl md:text-3xl font-bold mb-2">احصل على تقييم مجاني لمدى استعدادك للامتثال لقانون PDPL المصري</h3><p class="opacity-90 mb-6 max-w-xl mx-auto" style="color:hsl(var(--primary-foreground))">مكالمة لمدة 30 دقيقة، بدون عروض تقديمية — نقوم بمقارنة إعداد المستندات الحالي لديك بمتطلبات القانون 151/2020 ونقدم لك قائمة بالثغرات مرتبة حسب الأولوية يمكنك اتخاذ إجراء بشأنها على الفور.</p><a href="/contact" class="inline-flex items-center gap-2 rounded-full px-6 py-3 font-semibold hover:opacity-90 transition" style="background:hsl(var(--accent));color:hsl(var(--accent-foreground))">→ احجز مراجعة امتثال في مصر</a></div>' WHERE slug='egypt-pdpl-law-151-2020-compliance-guide';